defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

settings:
    is_distributed: False

data:
    images_path: /coco/train2017/
    annotations_path: /coco/annotations/captions_train2017.json
    image_size: [224, 224]
    context_length: 77
    shuffle_captions: False
    batch_size: 64

model:
    from_pretrained: True
    proj_dim: 256
    

algorithm:
    loss: clip